### ISSUE TITLE
soss-websocket yaml problem

### ISSUE THREAD

**Issue by Lenskiy** [eProsima/Integration-Service#28]
I am trying to connect to a server via a websocket and then subscribe to a topic. i\It seems that the connection is successful but then I am getting a TLS handshake error. Here is my config file
```
systems:
  ws_client:
  {
    type: websocket_client,
    host: echo.websocket.org,
    port: 443,
    node_name: "ws_client",
    authentication: {}
  }

  mock:
  {
    type: mock
  }

routes:
  engine_to_wsclient: { from: mock, to: ws_client }
  wsclient_to_engine: { from: ws_client, to: mock }

topics:
  client_to_engine: { type: "websocket_test/ClientToServer", route: wsclient_to_engine }
  engine_to_client: { type: "websocket_test/ServerToClient", route: engine_to_wsclient }
```

I run it as `soss sample-websocket-client-config.yaml`. Here is the error I receive
```
[2020-01-27 20:08:45] [connect] Successful connection
[2020-01-27 20:08:45] [error] handle_transport_init received error: TLS handshake failed
[2020-01-27 20:08:45] [fail] WebSocket Connection 174.129.224.73:443 - "" / 0 websocketpp.transport.asio.socket:8 TLS handshake failed
[2020-01-27 20:08:45] [info] asio async_shutdown error: asio.ssl:336462231 (shutdown while in init)
[soss::websocket::Client] Failed to establish a connection to the host [wss://echo.websocket.org:443]. We will periodically attempt to reconnect.
```

(1) What should I change to handshake successfully?
(2) How can I send a subscription command?

**Comment by mxgrey** [comment]
My first guess would be it's an issue with authentication. I don't think we've tested the websocket server/client without authentication. While unauthenticated connections are not recommended, it does make sense for us to support it for academic/experimental use.

**Comment by jamoralp** [comment]
I am closing this since it has been inactive for a long time, but please have in mind two considerations:

* For your `websocket_client` system, you were trying to set as a host `websocket.org/echo.html` website, which is another WebSocket client. This will not work, since you need to set up a WebSocket server.

* In the [3.0.0 release](https://github.com/eProsima/Integration-Service/releases/tag/v3.0.0), we have added an option to disable security and use a TCP endpoint for the WebSocket System Handle. Check it out in the [WebSocket System Handle documentation](https://integration-service.docs.eprosima.com/en/latest/user_manual/systemhandle/websocket_sh.html#configuration):
    ```yaml
    systems:
        websocket:
            type: websocket_client
            security: none
    ```
