### ISSUE TITLE
int16 or int32 as service request type makes soss-websocket segfault

### ISSUE THREAD

**Issue by janandries** [eProsima/Integration-Service#36]
When I use a service interface that accepts a `int16` (or `int32`) as a parameter for the request, for example:
```
# test_interface/test.srv
int16 input
---
bool output
```
and make a soss-websocket <-> ros bridge, `soss-websocket` gives a segmentation fault when this service is called from a websocket client using the following json:
```
{ "op":"call_service","service":"test_interface/test","args":{"input":1} }
```
If I change the service message to `uint8`, `int8` it works as expected. As said, it segfaults for both `int16` and `int32` types, I haven't tested more datatypes.

**Comment by koonpeng** [comment]
I found the underlying cause of this, json does not differentiate between signed and unsigned integers, the type used by soss is dependent on the how the json library interprets messages, sometimes it can tag a positive integer as unsigned.

https://github.com/osrf/soss/blob/1fff22320be0067955b227a98aa5b5fee4e02b0e/packages/json/src/conversion.cpp#L56-L63

as soss is trying to convert that to a signed integer, an error occurs here

https://github.com/osrf/soss/blob/1fff22320be0067955b227a98aa5b5fee4e02b0e/packages/core/include/soss/utilities.hpp#L282

the catch here is that `*from->second.cast<soss_type>()` does not actually perform type casting, it just checks if the pointer is the same type, in this case the pointer in the field is `uint64_t*` (due to soss promoting all ints to 64-bit) and we are trying to "cast" it to `int64_t*`, it sees that they are incompatible and returns a `nullptr`.

**Comment by koonpeng** [comment]
The best fix would probably be having `cast` perform bounds checking for primitive types instead of relying simply on the pointer type.

**Comment by koonpeng** [comment]
fixed
