### ISSUE TITLE
is-ros2-rosidl not found

### ISSUE THREAD

**Issue by gc-robotics** [eProsima/Integration-Service#81]
Hey! 

I am trying to build IS for ROS2 using the following repos:

RUN git clone https://github.com/eProsima/Integration-Service.git --recursive
RUN git clone https://github.com/eProsima/FastDDS-SH.git --recursive
RUN git clone https://github.com/eProsima/ROS2-Integration-Service.git --recursive
RUN git clone https://github.com/eProsima/ROS2-SH.git --recursive

Not sure whether they are the right ones as no clear information are provided.

When  ROSdep, I get:

RUN rosdep update \
    && rosdep install --from-paths src --ignore-src

`--- stderr: is-ros2-rosidl
CMake Error at CMakeLists.txt:22 (find_package):
  By not providing "Findis-core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "is-core", but
  CMake did not find one.

  Could not find a package configuration file provided by "is-core" with any
  of the following names:

    is-coreConfig.cmake
    is-core-config.cmake

  Add the installation prefix of "is-core" to CMAKE_PREFIX_PATH or set
  "is-core_DIR" to a directory containing one of the above files.  If
  "is-core" provides a separate development package or SDK, be sure it has
  been installed.

---
Failed   <<< is-ros2-rosidl [1.36s, exited with code 1]
`

Any idea? thanks in advance.

**Comment by jamoralp** [comment]
Good morning. First of all, you should not download the https://github.com/eProsima/ROS2-Integration-Service.git as it is terribly outdated and could cause nothing but trouble during the build process. I will speak with my colleagues at eProsima to tag this repository as outdated or make it private, but it is definitely an issue right now.

Your issue seems a bit strange. Could you please follow [this tutorial](https://integration-service.docs.eprosima.com/en/latest/dds-ros2.html) and see if the error persists?
Any commentaries on how the tutorial could be improved are welcome and very helpful to us. Thanks!

**Comment by gc-robotics** [comment]
Hi Antonio,

Roger that.
I will give it a go and get back to you with summarized results.

Thanks for now.
________________________________

**Comment by jamoralp** [comment]
Closing since inactive for more than a month now. Please do not hesitate to reopen if any issue arises. Thank you!
